[tool.poetry]
name = "uncle-joes-api"
version = "0.1.0"
description = "FastAPI backend for the Uncle Joe's Coffee Company web application"
authors = ["Somin Yang"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
uvicorn = {extras = ["standard"], version = "^0.30.0"}
google-cloud-bigquery = "^3.25.0"
bcrypt = "^4.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"